import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import type { Metadata } from "next";
import "../styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Link
          className="flex flex-col m-2 pl-1 w-14 h-14 text-left justify-end border-1"
          href="/"
        >
          <p className="text-xs font-bold">Explore</p>
          <p className="text-xs font-bold">AIC API</p>
        </Link>
        {children}
      </body>
    </html>
  );
}
